# Generated by Django 4.1.4 on 2023-01-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='options',
            field=models.CharField(blank=True, choices=[('BEERSHEVA', 'beer-sheva'), ('TELAVIV', 'tel-aviv')], default=None, max_length=20, null=True),
        ),
    ]
