# Generated by Django 4.1.4 on 2023-01-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='options',
            field=models.CharField(blank=True, choices=[('BEERSHEVA', 'Beer Sheva'), ('TELAVIV', 'Tel Aviv'), ('ASHDOD', 'Ashdod'), ('HAIFA', 'HAIFA'), ('RHOVOT', 'Rhovot'), ('JERUSALEM', 'Jerusalem')], default=None, max_length=20, null=True),
        ),
    ]
