# Generated by Django 4.1.4 on 2023-01-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_user_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='options',
            new_name='city',
        ),
    ]
