# Generated by Django 4.1.4 on 2023-01-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schedulemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulemodel',
            old_name='userReciever',
            new_name='Reciever',
        ),
    ]
